---
# tasks file for setNTPservers
- name: Set {{ attribute_name }} to {{ attribute_value }}
  community.general.ilo_redfish_config:
    category: Manager
    command: SetNTPServers
    baseuri: "{{ baseuri }}"
    username: "{{ username }}"
    password: "{{ password }}"
    attribute_name: "{{ attribute_name }}"
    attribute_value: "{{ attribute_value }}"
