---
- hosts: myhosts
  connection: local
  gather_facts: False
  tasks:
    - name: Validate input provided by user
      fail:
        msg: "username/password or cert_file/key_file or auth_token is mandatory"
      when:
        - (username is not defined or password is not defined) and (cert_file is not defined or key_file is not defined) and (auth_token is not defined)

    - name: Fail when more than one valid authentication method is provided
      fail:
        msg: "Only one authentication method is allowed. Provide either username/password or cert_file/key_file or auth_token."
      when:
        - ((username is defined or password is defined) and (cert_file is defined or key_file is defined) and auth_token is defined) or
          ((username is defined or password is defined) and (cert_file is defined or key_file is defined)) or
          ((username is defined or password is defined) and auth_token is defined) or
          ((cert_file is defined or key_file is defined) and auth_token is defined)

    - name: Get network boot settings when username and password are defined
      block:
        - ilo_boot:
            category: Systems
            command: GetBootSettings
            baseuri: "{{ baseuri }}"
            username: "{{ username }}"
            password: "{{ password }}"
          register: network_boot_settings

        - name: Boot settings present in the server
          debug:
            msg: "{{ network_boot_settings }}"

      when: username is defined and password is defined

    - name: Get network boot settings when cert_file and key_file are defined
      block:
        - ilo_boot:
            category: Systems
            command: GetBootSettings
            baseuri: "{{ baseuri }}"
            cert_file: "{{ cert_file }}"
            key_file: "{{ key_file }}"
          register: network_boot_settings

        - name: Boot settings present in the server
          debug:
            msg: "{{ network_boot_settings }}"
        
      when: cert_file is defined and key_file is defined

    - name: Get network boot settings when auth_token is defined
      block:
        - ilo_boot:
            category: Systems
            command: GetBootSettings
            baseuri: "{{ baseuri }}"
            auth_token: "{{ auth_token }}"
          register: network_boot_settings

        - name: Boot settings present in the server
          debug:
            msg: "{{ network_boot_settings }}"
         
      when: auth_token is defined