---
- hosts: myhosts
  connection: local
  name: Add User
  gather_facts: False
  # vars_files: iLO_redfish.yml

  vars:
    - new_user: Bhavya_check2
    - new_pass: testpass
    - role_id: Administrator

  tasks:
    - name: Create session
      community.general.redfish_command:
        category: Sessions
        command: CreateSession
        baseuri: "{{ baseuri }}"
        username: "{{ username }}"
        password: "{{ password }}"
      register: result

    - name: Add user
      community.general.redfish_command:
        category: Accounts
        command: AddUser
        baseuri: "{{ baseuri }}"
       #  username: "{{ username }}"
       #  password: "{{ password }}"
        new_username: "{{ new_user }}"
        new_password: "{{ new_pass }}"
        roleid: "{{ role_id }}"
        auth_token: "{{ result.session.token }}"
        
    - name: Delete session using security token created by CreateSesssion above
      community.general.redfish_command:
        category: Sessions
        command: DeleteSession
        baseuri: "{{ baseuri }}"
        auth_token: "{{ result.session.token }}"
        session_uri: "{{ result.session.uri }}"
