---
- hosts: myhosts
  connection: local
  name: Update user password
  gather_facts: False
  # vars_files: iLO_redfish.yml

  vars:
  - account_username: Bhavya_check1
  - account_updatename: Bhav

  tasks:
    - name: Create session
      redfish_command:
        category: Sessions
        command: CreateSession
        baseuri: "{{ baseuri }}"
        username: "{{ username }}"
        password: "{{ password }}"
      register: result

    - name: Update user name
      redfish_command:
        category: Accounts
        command: UpdateUserName
        baseuri: "{{ baseuri }}"
        # username: "{{ username }}"
        # password: "{{ password }}"
        account_username: "{{ account_username }}"
        account_updatename: "{{ account_updatename }}"
        auth_token: "{{ result.session.token }}"

    - name: Delete session using security token created by CreateSesssion above
      redfish_command:
        category: Sessions
        command: DeleteSession
        baseuri: "{{ baseuri }}"
        auth_token: "{{ result.session.token }}"
        session_uri: "{{ result.session.uri }}"
