---
- hosts: myhosts
  connection: local
  name: Power Supply (PSU) Inventory
  gather_facts: False
  vars_files: iLO_redfish.yml

  vars:
    datatype: PsuInventory

  tasks:
    - name: Create session
      redfish_command:
        category: Sessions
        command: CreateSession
        baseuri: "{{ baseuri }}"
        username: "{{ username }}"
        password: "{{ password }}"
      register: result

    - name: Define output file
      include_tasks: create_output_file.yml

    - name: Get PSU Inventory
      redfish_info:
        category: Chassis
        command: GetPsuInventory
        baseuri: "{{ baseuri }}"
        # username: "{{ username }}"
        # password: "{{ password }}"
        auth_token: "{{ result.session.token }}"
      register: result_psu

    - name: Copy results to output file
      copy:
        content: "{{ result_psu | to_nice_json }}"
        dest: "{{ template }}.json"

    - name: Delete session using security token created by CreateSesssion above
      redfish_command:
        category: Sessions
        command: DeleteSession
        baseuri: "{{ baseuri }}"
        auth_token: "{{ result.session.token }}"
        session_uri: "{{ result.session.uri }}"
