---
# tasks file for get_health_report
- name: Get Health Report
  community.general.redfish_info:
    category: Manager
    command: GetHealthReport
    baseuri: "{{ baseuri }}"
    # username: "{{ username }}"
    # password: "{{ password }}"
    auth_token: "{{ result.session.token }}"
  register: result_attr
